apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: toolbox
spec:
  selector:
    matchLabels:
      app: toolbox
  template:
    metadata:
      labels:
        app: toolbox
    spec:
      containers:
      - name: toolbox
        image: <RegistryLoginServer>/toolbox/toolbox:0.0.1
        ports:
        - containerPort: 22
        command: ["tail"]
        args: ["-f", "/dev/null"]
